config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'csv_uploader/show'
 
  root 'csv_uploader#show'

  post 'csv/send_data' => 'csv_uploader#get_data'
  get 'csv/show' => 'csv_uploader#show'
  post 'csv/delete' => 'csv_uploader#delete_data'
  get 'csv/download' => 'csv_uploader#download'


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	# To import data using csv file and saving in database 
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            user_hash = User.new
            user_hash.name = row[0]
            user_hash.email = row[1]
            user_hash.employee_id = row[2]
            user_hash.mobile_no = row[3]
            user_hash.save
        end
    end

    #export data from database to csv
    def self.to_csv(options = {})
     desired_columns = ["name", "employee_id", "email", "mobile_no"]
        CSV.generate(options) do |csv|
            csv << desired_columns
            all.each do |user|
                csv << user.attributes.values_at(*desired_columns)
            end
        end
    end
end

app/controllers/api/v1/base_controller.rb
#base_controller.rb

class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    render json: @blogs
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

      if @blog.save
        # format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        # format.json { render :show, status: :created, location: @blog }
        render :status => "200", :json => {:message => "success", blog: @blog}.to_json

      else
        # format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :business_nbame, :gst_no)
    end
end

app/controllers/csv_uploader_controller.rb
class CsvUploaderController < ApplicationController

def index
end

#to get data from csv file 
def get_data 
	# import method written in model 
	User.import(params[:user][:file]) 
	flash[:notice] = "Users uploaded successfully"
	redirect_to csv_show_path
end

#show the data from database 
def show 
	@data = User.all
end

 #To delete entry from database 
def delete_data	
	delete_data = params[:delete_users][:data].split(" ")
	User.where(id: delete_data).destroy_all
	redirect_to csv_show_path
end

# to download data as csv file 
def download 
	@user = User.all
	respond_to do |format|
		format.html
		format.csv { send_data @user.to_csv }
	end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_uploader_helper.rb
module CsvUploaderHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :business_nbame %>
    <%= form.text_field :business_nbame %>
  </div>

  <div class="field">
    <%= form.label :gst_no %>
    <%= form.number_field :gst_no %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Business nbame</th>
      <th>Gst no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.business_nbame %></td>
        <td><%= blog.gst_no %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<p>
  <strong>Business nbame:</strong>
  <%= @blog.business_nbame %>
</p>

<p>
  <strong>Gst no:</strong>
  <%= @blog.gst_no %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/csv_uploader/show.html.erb
<!-- Form to give upload botton for csv -->
<%= form_with scope: :user, url: csv_send_data_path , local: true do |form| %>
	
	<p>
		<%= form.label :file %><br>
		<%= form.file_field :file %>
	</p>

	<p>
		<%= form.submit %>
		</p>
<% end %>
<%= link_to "Download CSV", csv_download_path(format: "csv") %>

<html>
<head>
    <!-- plugin and cdn from dataatble.net to add jquery datatable -->
<link rel="stylesheet"  href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script  src ="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script >
<script type="text/javascript">
$(document).ready( function () {
    $('#myTable').DataTable();
} );
</script>
</head>

<table id="myTable" class="display">
    <thead>
        <tr>
        	<th></th>
            <th>Name</th>
            <th>Email</th>
            <th>Employee Id </th>
            <th>Mobile No.</th>
        </tr>
    </thead>
    <tbody>
    	<% @data.each do |data| %>
        <tr>
        	 <td><input type="checkbox" value="<%= data.id%>" class="delete-user" id="<%=data.id %>"></td>
            <td><%= data.name%></td>
            <td><%= data.email %></td>
            <td><%= data.employee_id%></td>
            <td><%= data.mobile_no %></td>
        </tr>
        <%end%>
    </tbody>
</table>
<!-- Delete button -->
<%= form_with scope: :delete_users, url: csv_delete_path , local: true do |form| %>
    <p>
        <%= form.hidden_field :data , id: "duser" %>
    </p>

    <p>
        <%= form.submit  'Delete Selected' %>
    </p>
<% end %>

<script type="text/javascript">
// to pass the selected checkbox data to params
    $('.delete-user').on('click', function (argument) {
      if($(this).prop('checked') == true){
    $('#duser').val($('#duser').val()+" "+this.id);
}else{
    var array = $('#duser').val().split(" ")
    var index = array.indexOf(this.id);
if (index > -1) {
  array.splice(index, 1);
  $('#duser').val(array.join(" "));
}

}
      
    })
</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvUploadeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>